### ISSUE TITLE
If download of data files fail, they get zeroed out.

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#2]
Hi there,

Your file download function `DownloadFile()` returns a boolean that you do not check and blindly update the data files.

I've noticed that the files get truncated to 0 bytes due to Issue #1. But any other network issue could blank the files and the data is gone. The site could be down: github does have had issues before. If someone is on a mobile connection and it fails. And you can imagine some other issues...

Thanks in advance,
Gus

**Comment by gcarreno** [comment]
Hi there,

Oh, BTW, if you want me to do a PR to correct this issue, just say so.
I'm sorry I should've stated that on the initial issue message, really sorry!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hi there,

You have also fixed this issue. Closing.

Cheers,
Gus

**Comment by wp-xyz** [comment]
Thanks for reporting.

**Comment by gcarreno** [comment]
No probs, quite welcome!!
