### ISSUE TITLE
Do you want me to provide multiplatform binaries and/or an InnoSetup install binary?

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#20]
Hey Werner (@wp-xyz),

I'm sure that your lack of GIT grasp includes creating tags. That's alright, no problems!

But it would be nice for people to have a pre-compiled binary they could download and run, instead of being savvy enough to download the source and compile it. That would reside on the Release area of GitHub.

On my _rig_ I'm able to compile(Linux-x86_64, Linux-arm[RasPi 3]) and cross-compile(Linux-i386, Win64-x86_64, Win32-i386), and I have enough competence to create an [Inno-Setup](https://jrsoftware.org/isinfo.php)([GitHub](https://github.com/jrsoftware/issrc)) that can decide to install either a Windows 32b or a Windows 64b version depending on the users platform. 
I'm still trying to automate the creation of `*.deb` packages with [this](https://github.com/sysrpl/Lazarus.Apps.Makedeb) and I'm not sure I would be inclined to do an `*.rpm`.
And finally, also provide a simple `*.tar.gz` and `*.zip` distribution for those that don't want to commit to a full install.
You can see an example of what I'm suggesting on my [lazJSONViewer Releases](https://github.com/gcarreno/laz-JSON-Viewer/releases) under the assets. All my suggestions are there, apart from the `*.deb`, which I'm still trying to get my head around.

If you agree to this, let me warn you, I may need write access to the repo. I would never mess with the code, because to be quite honest I'm oblivious of the data math/maths you're performing. I would only mess about with a script for Inno-Setup and maybe one to automatically produce the `*.zip/*.tar.gz` files.

If you don't want me to have write access to your repo, you could provide a back channel for me to supply the binaries and I can try to help you do the versioning and the tagging. This could also work.

I do not intend to put any pressure on you. If you're not comfortable with any of my suggestions, just brush me off with any excuse, since it's your _baby_ and I don't want to mess with that!!!

Cheers,
Gus

**Comment by wp-xyz** [comment]
My main intention is not to distribute binaries to the end user, my main interest is in contribution to the Lazarus community and to write some programs for my own needs. But on the other hand, having a full-blown application in the repo certainly would be interesting, at least as a template if once I'd need it.

So please, go ahead, I invited you to particate in this repository. (I hope that "invitation" includes write access - oh boy, these guthub people are able to write the most confusing web sites. Recently I wanted to delete a repo from gibhub, it took me half an hour to find how to do this).

**Comment by gcarreno** [comment]
Hey Werner (@wp-xyz)

> But on the other hand, having a full-blown application in the repo certainly would be interesting, at least as a template if once I'd need it.

Yes, thank you, because that's what I was thinking when I began to talk to you: You wanna learn as bad as I did, like, a year ago.
I actually decided, poorly, to ask how to use git from a friend that isn't that good at passing his knowledge, but that was my fault. I then had to do it the hard way: Google, trial and (loads of) error. And I even bought access to an [online video course](https://gettinggit.com/) for the basics of GIT. That helped me quite a lot!!

AND... this will actually be a first for me in terms of collaboration. I've been solo for so much that I've gotten cosy in my methods. With a co-_conspirator_ that means I have to perform LOADS of `git pull`s before I begin coding sessions, eheheh

In terms of the application template, I can give you my interpretation of it and we can discuss if you like it and what you wanna change. For this, I would advise you to start the discussions. It's a new thing, kinda like a forum and you turn it on:
1. Settings
2. Options (Should be the one already selected on the left)
3. Inside the Features box
4. Check mark the Discussions

This way we don't pollute the issues with this type of conversation. Issues should only be used for Bug Reports and Feature Requests. I'll assemble a template for both of those for your approval.

> I hope that "invitation" includes write access

The invite was good and I now have `push` ability to the repo. But that's it, all the Settings and ownership are all with you. I don't even know if I can accept PRs. See, I'm still a newbie :stuck_out_tongue: 

> Recently I wanted to delete a repo from GitHub, it took me half an hour to find how to do this

Yeah, putting that option at the end of such a long list of things under Settings->Options isn't really good design :-\

Well, don't hesitate to ask. Anything, I mean it, anything. Please do!!!
I may not have all the answers, but I'll gladly share what I've accumulated and what I don't know, I'll just ask for your patience until I can find out!

The last thing I wanna say is: **THANK YOU SOOOO MUCH** for trusting me. Trust is something hard to share with a stranger and I do **REALLY** appreciate your gesture!!

Cheers,
Gus

PS: I'll wait for you to get Discussions going so we can plan next moves.

**Comment by wp-xyz** [comment]
Discussions set up.

But let me ask a question here still: Whenever I go to the corona repository today I see that there is a pullrequest #19 to be merged. But I already did that yesterday. How to get rid of this message?

**Comment by gcarreno** [comment]
Thanks for the discussions!!

Now, when you say message, can you be a bit more specific?
Is it on the notifications?

**Comment by wp-xyz** [comment]
I mean the note surrounded by red rect:
![grafik](https://user-images.githubusercontent.com/30792460/107702002-ef089a00-6cb9-11eb-8275-8228a6f70e23.png)

**Comment by gcarreno** [comment]
That seems to be the last commit you made to branch master.

You then started committing to your new branch.

At least from the `git log` on my side.

**Comment by gcarreno** [comment]
I'm closing this one.

I think we agreed to it, just need to iron out my cross-compiling issues.

Will start with version 1.0.0 with only the compressed binaries and will evolve to install packages once we get a consistent binary output.
