### ISSUE TITLE
File Download using WinInet, source and win32 binary

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#29]
Hey Werner(@wp-xyz),

Found the source I was looking for. I was clever, had it on a private repo on GitHub, ufff.

The only thing I need to suss out now, is how to hook up the download progress.

I'm including source and a `i386-win32` cross-compile. Could you test the `*.exe` with your virus software? THANKS!!
[lazHeidiSQL-UpdateCheck-i386-win32-source.zip](https://github.com/wp-xyz/corona/files/6014091/lazHeidiSQL-UpdateCheck-i386-win32-source.zip)

If using `WinInet` fools the anti-virus, I have a big fat rewrite ahead of me :smile: 

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

Version with download progress (source, binary compiled with no debug data):
[lazHeidiSQL-UpdateCheck-i386-win32-source.zip](https://github.com/wp-xyz/corona/files/6014147/lazHeidiSQL-UpdateCheck-i386-win32-source.zip)

Could you please test both under anti-virus?
One has dbg data(above) and other is with no dbg data(this one).

Many thanks!!

Cheers,
Gus

**Comment by wp-xyz** [comment]
Am 20.02.2021 um 05:57 schrieb Gustavo Carreno:
>
> Version with download progress (source, binary compiled with no debug
> data):
> lazHeidiSQL-UpdateCheck-i386-win32-source.zip
> <https://github.com/wp-xyz/corona/files/6014147/lazHeidiSQL-UpdateCheck-i386-win32-source.zip>
>
> Could you please test both under anti-virus?
> One has dbg data(above) and other is with no dbg data(this one).
>
I thought an exe is included in the zip. But I can't find it... The same
with the other mail.

**Comment by wp-xyz** [comment]
Would usage of wininet mean that we would not have to distribute the openssl dlls along with the exe?

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

It seems that my `zip` is making really crappy `*.zip` files that segfault midnight commander(mc) and doesn't show the `*.exe` using the Archive Manager. What pisses me off is that if I use the `unzip` command, it unzips the `*.exe`. Go figure!! Another gremlin in my machine, ARGGGG

Here's a `*.tar.gz` one:
[lazHeidiSQL-UpdateCheck-i386-win32-source.tar.gz](https://github.com/wp-xyz/corona/files/6016047/lazHeidiSQL-UpdateCheck-i386-win32-source.tar.gz)

> Would usage of wininet mean that we would not have to distribute the openssl dlls along with the exe?

Unfortunately, I'm afraid not. HeidiSQL still distributes the ssl dlls.

Cheers,
Gus

**Comment by wp-xyz** [comment]
> Here's a `*.tar.gz` one:
> [lazHeidiSQL-UpdateCheck-i386-win32-source.tar.gz](https://github.com/wp-xyz/corona/files/6016047/lazHeidiSQL-UpdateCheck-i386-win32-source.tar.gz)

No antivirus alarm from these files, even when I run them out of the zip

BTW, with "run out of the zip" I mean: I have PowerArchiver to open compressed files and it displays the zip contents in a nice GUI from which I can view files or run binaries without having to unzip the entire archive (the program, probably, unzips the requested files to the temp folder).

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

> No antivirus alarm from these files, even when I run them out of the zip

That's awesome!
But now I'm baffled, since you mention on the other issue that my cross-compiled `corona.exe` also didn't trip the alarm.

> BTW, with "run out of the zip" I mean: [...]

Yeah, all the GUI archive managers allow you to do this :smile: 

Cheers,
Gus

**Comment by gcarreno** [comment]
Closing since you told me this won't be needed due to temporary anti-virus glitch is solved.

Please re-open if you think we should use this _native_ windows API.
