### ISSUE TITLE
Humble question: Why are you not using TIniPropStorage?

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#32]
Hi Werner(@wp-xyz),

I'm not trying to be condescending AT ALL, but I've just noticed that you're using a `TIniFile` to save component state and doing all the the thing by hand like:
1. read setting from ini section
2. write value to component property
3. read component property
4. write value to ini section

I hope you are aware of `TXMLPropStorage`, `TIniPropStorage` and `TJSONPropStorage`(I'm rather proud of having done this last one and having it included in the main Lazarus repo :smile:)
Once you drop one a those on a form and set the `TForm.SessionProprties`, the app takes care of all the read/load/save/write cycle.
And you can even add more stuff via `TIniPropStorage.StoredValues` for other config related stuff.

If it's by choice, I would love to hear what's your experience to not using them.

Cheers,
Gus

**Comment by wp-xyz** [comment]
I am used to writing storage by myself. This way I can control everything: what is happening and where. I can name the stored items as I like (no component names), and I find everything at one place (no scattered over Object Inspector and event handlers).

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz),

All valid points, thanks for sharing!!

I'm more of an automation person, you prize control a bit more, no probs!!
I'm at a point where I don't trust my memory to remember all this stuff in case I need a big refactor, so I rely on automation, or delegation I guess.

Cheers,
Gus
