### ISSUE TITLE
Checkbobx Group "Cases" size

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#33]
Hey Werner(@wp-xyz),

Sorry to bother with another size issue:
![corona-checkbox-group-size](https://user-images.githubusercontent.com/81799/108896695-273e9f80-760d-11eb-9845-48ff1b286244.png)

As you can see, the "Cases" Checkbox Group now has a scrollbar.

Cheers,
Gus

**Comment by wp-xyz** [comment]
I know. The CheckListbox has no AutoSize property - I must calculate the height by myself, and it seems that I am off by a few pixels in Linux. Now I added a splitter below the Time series data groupbox so that the the user can adjust the height which is stored in the ini file.

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz)

Jeezzz, I'm now feeling your pain with these micro-adjustment!! It's an effin' pain in the arse!!

Okydokes, do you want me to continue testing on this or should you and then you also close?

Cheers,
Gus

**Comment by wp-xyz** [comment]
I still have a few issues on the list. So, better if you start testing when all is in master.

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz),

> I still have a few issues on the list. So, better if you start testing when all is in master.

I'm all good with that!!

Cheers,
Gus
