### ISSUE TITLE
Commit cd18508 fixes compile but doesn't make it work

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#35]
Hey Werner(@wp-xyz),

Commit cd18508 does allow compilations below FPC 3.2.0, but it does not make it work.

I'll take care of this personally, so don't worry too much about it.

I'll commit it to `master` when it works and you can replicate it under `mapping` after.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz),

Hummm, this is gonna take a bit more time that I anticipated.

I'm stumbling on some issues with the SSL context not being initialized even after I follow all the steps under [fphhtpclient](https://wiki.freepascal.org/fphttpclient) which is still pre FPC 3.2.0.

Might be more gremlins on my side. We have proven that it's a thing...

I'm testing on the source code I provided you earlier so I don't mess around with `master`.

Cheers,
Gus

**Comment by wp-xyz** [comment]
Please look in the repo at my original code before I replaced it with your modal form. There was a forum user, I think it was dbannon, who optimized the SSL part a lot, and this was on fpc3.0.4. I forgot about this when I added your code

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz),

Since you didn't remove `cdownloader.pas` it's still there.
Had a look and I think I now what to do. Will do it tomorrow.

Thanks for the hint. I was under suspicion it would be something like a call back for SSL, but it wasn't mentioned on the wiki and I completely forgot where I saw it. I think it was your `cdownloader.pas` actually, eheheh

Thanks again Werner!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

I couldn't stay put after I answered last, so I got my example working.
It has loads of `{$IF FPC_FULLVERSION etc}` and it's not elegant, but it works from 2.0.6 upwards.
On Lazarus 2.0.6 is when you first get FPC 3.0.4.

I'll ruminate a bit more on it so when I port it to corona, it's not messy.
Maybe put some of that mess on another unit, dunno yet.

Cheers,
Gus
PS: Now to get `setup-lazarus` up to date with Lazarus 2.0.12 release, humpffff :-\

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz),

Finally got around to make downloads work from FPC 3.0.4 up.
It's committed and I'll close this one.

Closed by: 76f6654

Cheers,
Gus
PS: And also got `setup-lazarus` up to date with Lazarus 2.0.12, YAY :raised_hands:

**Comment by wp-xyz** [comment]
> Finally got around to make downloads work from FPC 3.0.4 up.
> It's committed and I'll close this one.
>
> PS: And also got `setup-lazarus` up to date with Lazarus 2.0.12, YAY 🙌

Thanks

**Comment by gcarreno** [comment]
Quite welcome my friend!!
