### ISSUE TITLE
Please complete info under "About" and maybe license

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#39]
Hi Werner(@wp-xyz),

I understand that when you created this repo you weren't planning on having someone like me nagging about completeness, but now that I've worked my magic in having you aboard with said completeness, could you address these info issues? (I would do it myself, but I can't change repo stuff)

1. On the "About" section, please click on the gear symbol and fill out at least the description and some Topics:
  - `freepascal`
  - `free-pascal`
  - `fpc`
  - `lazarus`
  - `lazarus-ide`
  - `covid-19`
  - `data`
  - `data-science`
  - `data-visualization`
  - `data-analysis`
  - `covid`
  - `covid-19`
  - `covid-data`
  - And whatever more you think is necvessary
2. I know you don't give a flying effe about licenses, but can you please select one? Suggestions since it's science related:
  - GPL v3
  - One of the CC ones, you choose the best one that fits
  - Or the Unlicense one if you really don't give a effe about copyright and stuff

This does not affect the release and we can discuss it with time to spare.

Cheers,
Gus

**Comment by wp-xyz** [comment]
Added some topics. But where's the license settings?

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

You choose one and drop a file called LICENSE with it's contents. GitHub will then pick it up from there.
You can find a comprehensive list here: https://opensource.org/licenses

Cheers,
gus

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

And don't forget the Description!! :stuck_out_tongue_winking_eye: 

Cheers,
Gus

**Comment by wp-xyz** [comment]
Sorry, had forgotten about it.

Reading these license texts makes me aggressive... Can you propose one? The software should be free, but must not be sold by anybody. If somebody makes derivative work he/she should refer to this site as being the origin of their work.

**Comment by gcarreno** [comment]
Hey Werner(@wp-xyz),

I'm not an open source layer, but to me what you're asking for looks like GPL v3.
But I still have to look at what license the data we are using is under to see if we can host it under the repo or if we can't then it has to be downloaded by the user, first time.
Or if the license the data is under, influences this repo's license.
Yes I know, it's complicated and rather a pain in the arse, but it's the reality we live in, humph!! ¯\_(ツ)_/¯

Cheers,
Gus
