### ISSUE TITLE
Visual indication on the graph of "when" the map slider is

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#41]
Hey Werner(@wp-xyz),

Does is make sense to have a visual representation on the graph of _when_ the map slider is?
I dunno, like a red (or something along a good colour for visual distinctness) vertical line?

Cheers,
Gus

**Comment by wp-xyz** [comment]
It's already there. In the ChartListbox next to the timeseries chart, the first entry is "Date indicator" - when checked it displays a purple vertical bar which follows the date slider.

(Ah, it should be hidden when the map is not displayed...)

**Comment by gcarreno** [comment]
Hi Werner(@wp-xyz),
> It's already there.

:facepalm: 

I'm gonna close this one in shame, because I immediately remembered that checkbox when I looked at it, right after you mentioned it.

Sorry for being so daft!!

Cheers,
Gus
