### ISSUE TITLE
Friendly enquiry about data not being updated

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#49]
Hey WP (@wp-xyz ),

Just a friendly enquiry to see if you have any idea why the data has stopped being updated as of 8 Mar 2023?

Many thanks in advance!!

Cheers,
Gus

**Comment by wp-xyz** [comment]
The pandemic is over...

From the JHU site from which I am pulling the data: _"On March 10, 2023, the Johns Hopkins Coronavirus Resource Center ceased its collecting and reporting of global COVID-19 data. "_
