### ISSUE TITLE
Overlaping buttons and treeview

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#8]
Hi there,

![corona-ovelap](https://user-images.githubusercontent.com/81799/77269122-e07b5380-6c9f-11ea-86ae-18e8957fde99.png)

As you can see `btnUpdate` and `btnClear` are overlapping the `TreeView`.

And the `MinWidth` for the `LeftPanel` is eating up on the text on `rgDataType`.

I'm not completely sure that this is your fault, I think Lazarus behaves a bit diff in Windows and Linux in terms of the grid, I think. And I'm not sure I haven't messed with the grid defaults myself.
Shouldn't make any diff, but hey, who knows?!?!?

Could you, please, post an image of how it looks when your first run it? Pls delete `corona.cfg` first :)

Many thanks in advance,
Gus

**Comment by wp-xyz** [comment]
Should be fixed with recent introduction of BeforeRun method.

**Comment by gcarreno** [comment]
Hey there,

Like I said in a comment on issue #10 I ran the code with `BeforeRun()` in a clean new pull and nothing changed.

I can guaranty i'st clean because I have a `corona.git` folder where I pull into and a `corona` folder where I delete everything and copy all but the `.git` folder. Then `lazbuild` or IDE build/compile from there.

Again, like I said, no change. `LeftPanel.MinWidth` is not affected by the `BeforeRun` and the buttons are still overlapping the `TreeView`.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey there,

I've just made a compare between what's on the IDE:

![corona-in-lazarus](https://user-images.githubusercontent.com/81799/77353737-6d262000-6d39-11ea-9636-06fa856d3c34.png)

and what happens on a clean run:

![corona-no-change](https://user-images.githubusercontent.com/81799/77353760-7dd69600-6d39-11ea-98fa-1610cc9a51ea.png)

and it actually shrinks. There is something quite odd with my system!!!

But the buttons overlap the `TreeView` both in Design and runtime...

Cheers,
Gus
