### ISSUE TITLE
Very humble suggestion for config load/save and another prettifying suggestion.

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#9]
Hi there,

This zip: [Application_Config_Demo.zip](https://github.com/wp-xyz/corona/files/4366897/Application_Config_Demo.zip) is my boilerplate for any application which I do some config saving.

If you're into the whole "More is Less" refactoring thing, this will cut a fair chunk of your code and it will enable you to add stuff to the config a LOT quicker and seamlessly.

I also introduce you to `TPairSplitter`. Once I found this one, I just love it to bits ;)

Cheers,
Gus

**Comment by wp-xyz** [comment]
Thanks for showing me your config demo. Everybody has his own favorites. I try to use as little non-standard code as much as possible unless it provides needed features. It will just cause trouble later. I could use the PropStorage components, but I am not used to them. Typing the ini code is not a problem, and I know absolutely what is happening.

**Comment by gcarreno** [comment]
Hey there,

Okydokes, I understand.

Just thought less babysitting something that is automated in a true and tested component that has been around forever would be a good thing.

I like it because instead of doing it by code, I just update a list of properties in a very helpful form and that's it, no more fuss.

But as you say, each is own ;)

Cheers,
Gus
